version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3.8 bot.py
    volumes:
      - .:/app-bot
    environment:
      TO_CHAT_ID: none
      TG_TOKEN: none